apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: monitoring
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.priority: "50"
    traefik.ingress.kubernetes.io/service.nativelb: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - pr-tracker.dev
      secretName: pr-tracker-tls
  rules:
    - host: pr-tracker.dev
      http:
        paths:
          - path: /grafana
            pathType: Prefix
            backend:
              service:
                name: kube-prometheus-stack-grafana
                port:
                  number: 80
