apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: ghcr.io/dhruv1249/pr-tracker-auth:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5005
        env:
        - name: PORT
          value: "5005"
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: pr-tracker-config
              key: node-env
        - name: PROXY_URL
          value: "http://service-router:5003"
        - name: CLIENT_URL
          valueFrom:
            configMapKeyRef:
              name: pr-tracker-config
              key: client-url
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: pr-tracker-secrets
              key: mongodb-uri
        - name: GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: pr-tracker-secrets
              key: github-client-id
        - name: GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: pr-tracker-secrets
              key: github-client-secret
        - name: ENCRYPTION_SECRET
          valueFrom:
            secretKeyRef:
              name: pr-tracker-secrets
              key: encryption-secret
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: pr-tracker-secrets
              key: jwt-secret
        - name: INTERNAL_SECRET
          valueFrom:
            secretKeyRef:
              name: pr-tracker-secrets
              key: internal-secret
---
apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  selector:
    app: auth
  ports:
  - protocol: TCP
    port: 5005
    targetPort: 5005
